# Generated by Django 4.2.20 on 2025-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_loginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='userId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
