# Generated by Django 4.2.20 on 2025-03-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='userId',
            field=models.CharField(default=1, max_length=50, verbose_name='User Id'),
            preserve_default=False,
        ),
    ]
