# Generated by Django 5.1.7 on 2025-03-20 17:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_groups_staff_is_active_staff_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='userId',
            field=models.CharField(blank=True, max_length=50, verbose_name='User ID'),
        ),
    ]
